All of my changes

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -37,11 +37,49 @@ abort() {
   if [ ! -f /tmp/anykernel/anykernel.sh -o "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
     cleanup;
   fi;
-  umount /system;
-  umount /vendor 2>/dev/null;
-  umount /data 2>/dev/null;
+  umount -l /system_root 2>/dev/null
+  umount -l /system 2>/dev/null
+  umount -l /vendor 2>/dev/null
   exit 1;
 }
+is_mounted() {
+  TARGET="`readlink -f $1`"
+  cat /proc/mounts | grep " $TARGET " >/dev/null
+  return $?
+}
+mount_system() { 
+  # Check A/B slot
+  slot=`getprop ro.boot.slot_suffix`
+  if [ -z $slot ]; then
+    slot=_`getprop ro.boot.slot`
+    [ $slot = "_" ] && slot=
+  fi
+  [ -z $slot ] || ui_print "A/B partition detected, current slot: $slot"
+  is_mounted /system || [ -f /system/build.prop ] || mount -o rw /system 2>/dev/null
+  if ! is_mounted /system && ! [ -f /system/build.prop ]; then
+    SYSTEMBLOCK=`find /dev/block -iname system$slot | head -n 1`
+    mount -t ext4 -o rw $SYSTEMBLOCK /system
+  fi
+  is_mounted /system || [ -f /system/build.prop ] || abort "! Cannot mount /system"
+  cat /proc/mounts | grep -E '/dev/root|/system_root' >/dev/null && SKIP_INITRAMFS=true || SKIP_INITRAMFS=false
+  if [ -f /system/init.rc ]; then
+    SKIP_INITRAMFS=true
+    mkdir /system_root 2>/dev/null
+    mount --move /system /system_root
+    mount -o bind /system_root/system /system
+  fi
+  $SKIP_INITRAMFS && ui_print "Device skip_initramfs detected"
+  if [ -L /system/vendor ]; then
+    # Seperate /vendor partition
+    is_mounted /vendor || mount -o rw /vendor 2>/dev/null
+    if ! is_mounted /vendor; then
+      VENDORBLOCK=`find /dev/block -iname vendor$SLOT | head -n 1`
+      mount -t ext4 -o rw $VENDORBLOCK /vendor
+    fi
+    is_mounted /vendor || abort "! Cannot mount /vendor"
+  fi
+  ui_print " "
+}                
 
 show_progress 1.34 4;
 ui_print " ";
@@ -75,12 +113,8 @@ ui_print "AnyKernel2 by osm0sis @ xda-developers";
 ui_print " ";
 ui_print " ";
 
-umount /system 2>/dev/null;
-umount /vendor 2>/dev/null;
-mount -o ro -t auto /system;
-mount -o ro -t auto /vendor 2>/dev/null;
+mount_system
 mount /data 2>/dev/null;
-test -f /system/system/build.prop && root=/system;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
   ui_print "Checking device...";
@@ -89,6 +123,7 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
     if [ "$(getprop ro.product.device)" == "$testname" -o "$(getprop ro.build.product)" == "$testname" ]; then
       ui_print "$testname";
       match=1;
+      break;      
     fi;
   done;
   ui_print " ";
@@ -104,6 +139,7 @@ done;
 if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
 fi;
+if [ -z $slot ]; then sed -i "/<slot>/d" /tmp/anykernel/tools/ak2-core.sh; else sed -i "s|<slot>|$slot|" /tmp/anykernel/tools/ak2-core.sh; fi
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
   abort;
@@ -112,8 +148,6 @@ fi;
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
   ui_print " ";
   ui_print "Pushing modules...";
-  mount -o rw,remount -t auto /system;
-  mount -o rw,remount -t auto /vendor 2>/dev/null;
   cd /tmp/anykernel/modules;
   for module in $(find . -name '*.ko'); do
     if [ ! -e /$module ]; then
@@ -130,8 +164,6 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
     fi;
   done;
   cd /tmp/anykernel;
-  mount -o ro,remount -t auto /system;
-  mount -o ro,remount -t auto /vendor 2>/dev/null;
 fi;
 
 debugging;
@@ -140,9 +172,9 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.cleanup)" == 1 ]; then
   cleanup;
 fi;
 
-umount /system;
-umount /vendor 2>/dev/null;
-umount /data 2>/dev/null;
+umount -l /system_root 2>/dev/null
+umount -l /system 2>/dev/null
+umount -l /vendor 2>/dev/null
 ui_print " ";
 ui_print " ";
 ui_print "Done!";
